logging:
  version: 1
  disable_existing_loggers: False

  formatters:
    default:
      format: '[%(asctime)s][%(levelname)-4.4s][%(name)20.20s](%(funcName)s): %(message)s'

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: default
      stream: ext://sys.stdout

  loggers:
    nordic_realm.di:
      level: INFO

  root:
    level: INFO
    handlers: [ console ]
    propagate: no